image: gradle:jdk8

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
  - .gradle/caches/
  - .gradle/wrapper/

test:
  stage: test
  script: ./gradlew check

#javadoc:
#  cache: {}
#  stage: deploy
#  script: javadoc -d public @javadoc.args
#  only:
#  - master
#  artifacts:
#    paths:
#    - public