image: gradle:jdk8

test:
  stage: test
  script:
  - if [ -d "$DIRECTORY" ]; then
      cd .gradle
      ls -la
      cd ..
    fi
  - ./gradlew check
  cache:
    key: test
    paths:
    - .gradle/