image: gradle:jdk8

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
  - .gradle/caches/
  - .gradle/wrapper/

test:
  stage: test
  script:
  - ./gradlew check

javadoc:
  stage: deploy
  script:
  - javadoc -protected -splitindex -author -version -d public