language: java
install: true

jdk:
- openjdk8

stages:
- test
- name: deploy
  if: type = push AND tag IS present

jobs:
  include:
  - stage: test
    script: "./gradlew check"
  - stage: deploy
    script:
    - "openssl aes-256-cbc -K $encrypted_0d982abece1d_key -iv $encrypted_0d982abece1d_iv -in maven-key.gpg.enc -out maven-key.gpg -d"
    - "./gradlew publish"
    on:
      branch: master
