language: java
install: true

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: ./gradlew check
    - stage: deploy
      script: ./gradlew publish