language: java
install: true

jdk:
- openjdk8

stages:
- test
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: test
    script: "./gradlew check"
  - stage: deploy
    script:
    - "openssl aes-256-cbc -K $encrypted_f183395f0c7d_key -iv $encrypted_f183395f0c7d_iv -in maven-key.gpg.enc -out maven-key.gpg -d"
    - "./gradlew publish"
